services:
  zookeeper:
    image: zookeeper:3.8.0
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "9092:9092"  # This maps the host port 9092 to the container port 9092
      - "9093:9093"  # Map the host port 9093 to the container port 9093
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093  # Change the outside listener port to 9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093  # Different ports for INSIDE and OUTSIDE
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE  # Set inter-broker listener name to INSIDE
    depends_on:
      - zookeeper

  create-topics:
    image: confluentinc/cp-kafka:latest  # Use the same image as Kafka
    depends_on:
      - kafka
    command: >
      bash -c "
      sleep 15 &&
      kafka-topics --create --topic CustomerInputTopic --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic CustomerEVEN --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1 &&
      kafka-topics --create --topic CustomerODD --bootstrap-server kafka:9092 --partitions 1 --replication-factor 1"

  springboot_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_PROFILES_ACTIVE: docker
